imports:
  - javascript
  - php

tools:
  php_code_sniffer:
    filter:
      excluded-paths: [ spec/*, .phpspec/* ]
    config:
      standard: PSR2

  php_analyzer:
    filter:
      excluded-paths: [ spec/*, .phpspec/* ]

  php_sim:
    filter:
      excluded-paths: [ spec/*, .phpspec/* ]

build_failure_conditions:
    - 'issues.label("coding-style").new.exists'

filter:
  excluded_paths:
    - docs/*
    - vendor/*
