checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 5.6
            ini:
                'date.timezone': 'Europe/Rome'
    tests:
        override:
            -
                command: 'vendor/bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
