
language: php

php:
  - 5.6
  - 7.0

cache:
    directories:
        - vendor

before_script: composer install --prefer-source --no-interaction

script: ./vendor/bin/phpspec run -fpretty --verbose

notifications:
    email: murru7@gmail.com